# Generated by Django 5.1.1 on 2024-09-24 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
